import { useRouter } from 'next/router'
import Head from 'next/head'
import Feed from './components/feed'
import styles from '../styles/Home.module.css'


export default function Home() {
  const router = useRouter()
  const currentPost = router.query.currentPost

  return (
    <div className={styles.container}>
      <Head>
        <title>Comentários</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       testes
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
